name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Login to GitHub Package Registry
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/didstopia/7dtd-json-api/7dtd-json-api:latest
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/didstopia/7dtd-json-api/7dtd-json-api:latest
