name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 7dtd-json-api:latest
    - name: Tag the Docker image
      run: docker tag 7dtd-json-api:latest docker.pkg.github.com/Didstopia/7dtd-json-api/7dtd-json-api:latest
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/Didstopia/7dtd-json-api/7dtd-json-api:latest
